### ISSUE TITLE
Unable to install dependencies from requirements.txt as part of an environment.yml

### ISSUE THREAD

**Issue by drorata** [conda/conda#10815]
## Current Behavior

In my `environment.yml` I install some of the dependencies from a `requirements.txt` using `pip`. 
This part of the dependencies resolving fails with a `CondaEnvException` exception. See below more details.

### Steps to Reproduce

Consider the following `environment.yml`:

```yml
name: my_env
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - jupyter
  - nb_conda
  - pip
  - jupyter_contrib_nbextensions
  - pip
  - pip:
      - -r file:requirements.txt
```

and the `requirements.txt`:

```
pandas~=1.0
yfinance~=0.1
pandas_datareader~=0.8
pytest<7.0
loguru<0.6
beautifulsoup4~=4.9
python-dotenv<0.20
click<9.0
sendgrid<7.0
```

Running either `conda env create -f environment.yml` or `conda env update -f environment.yml` fails with the following error:

```
Installing pip dependencies: | Ran pip subprocess with arguments:
['/Users/username/anaconda3/envs/stocks-opportunities-monitor/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/username/Dropbox/dev/stocks-opportunities-monitor/condaenv.812ekr2q.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 286, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 384, in get_requirements
    for parsed_req in parse_requirements(
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 135, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 319, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 348, in _parse_and_recurse
    yield from self._parse_and_recurse(req_path, nested_constraint)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 324, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 353, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 518, in get_file_content
    resp = session.get(url)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 697, in send
    r.content
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/username/anaconda3/envs/stocks-opportunities-monitor/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 769, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'

failed

CondaEnvException: Pip failed
```

It seems like the temporary copy of the `requirements.txt` is not available. Note that if I remove the last part:

```
  - pip:
      - -r file:requirements.txt
```

Then the environment is created properly and I can install the dependencies manually using `pip install -r requirements.txt`.

## Expected Behavior

Be able to create/update the environment directly with `conda`.

Note that the environment used to work seamlessly . I suspect that after updating `conda` to 4.10.3 the issue started. I tried to revert back to `4.10.1` but it didn't help. I don't remember what was the version of `conda` I had before the update.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : stocks-opportunities-monitor
    active env location : /Users/username/anaconda3/envs/stocks-opportunities-monitor
            shell level : 2
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.10.3
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/username/anaconda3  (writable)
      conda av data dir : /Users/username/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/username/anaconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/anaconda3/envs
                          /Users/username/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.8.5 Darwin/20.5.0 OSX/10.16
                UID:GID : 502:20
             netrc file : /Users/username/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/username/.condarc <==
changeps1: False
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/username/anaconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2            py39h6e9494a_1    conda-forge
argon2-cffi               20.1.0           py39h89e85a6_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    3.3.1              pyhd8ed1ab_0    conda-forge
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py39h6e9494a_0    conda-forge
cffi                      1.14.6           py39hb71fe58_0    conda-forge
charset-normalizer        2.0.3                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
dbus                      1.13.6               ha13b53f_2    conda-forge
debugpy                   1.4.1            py39h9fcab8e_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                he49afe7_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
glib                      2.68.3               he49afe7_0    conda-forge
glib-tools                2.68.3               he49afe7_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      3.2                      pypi_0    pypi
importlib-metadata        4.6.1            py39h6e9494a_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.0.3            py39h71a6800_0    conda-forge
ipython                   7.25.0           py39h71a6800_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py39h6e9494a_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py39h6e9494a_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.7.1            py39h6e9494a_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py39h6e9494a_1002    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py39h6e9494a_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
krb5                      1.19.1               hcfbf3a7_0    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libglib                   2.68.3               hd556434_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.3                 hea3049e_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
loguru                    0.5.3                    pypi_0    pypi
lxml                      4.6.3            py39hf41e7f8_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                2.0.1            py39h89e85a6_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py39h89e85a6_1004    conda-forge
multitasking              0.0.9                    pypi_0    pypi
mysql-common              8.0.25               h694c41f_2    conda-forge
mysql-libs                8.0.25               h115446f_2    conda-forge
nb_conda                  2.2.1            py39h6e9494a_4    conda-forge
nb_conda_kernels          2.3.1            py39h6e9494a_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py39h6e9494a_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
notebook                  6.4.0              pyha770c72_0    conda-forge
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.67                 h31e2bf1_0    conda-forge
numpy                     1.21.1                   pypi_0    pypi
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.1                    pypi_0    pypi
pandas-datareader         0.10.0                   pypi_0    pypi
pandoc                    2.14.1               h0d85af4_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1                   pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
prompt_toolkit            3.0.19               hd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0                   pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt-impl                 5.12.3           py39hef7122c_7    conda-forge
pyqt5-sip                 4.19.18          py39hd8f94c5_7    conda-forge
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyrsistent                0.17.3           py39h89e85a6_2    conda-forge
pytest                    6.2.4                    pypi_0    pypi
python                    3.9.5           hd187cdc_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.19.0                   pypi_0    pypi
python-http-client        3.3.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1            py39hcbf5805_0    conda-forge
pyzmq                     22.1.0           py39h7fec2f1_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
sendgrid                  6.7.1                    pypi_0    pypi
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.2.1                    pypi_0    pypi
sqlite                    3.36.0               h23a322b_0    conda-forge
starkbank-ecdsa           1.1.1                    pypi_0    pypi
terminado                 0.10.1           py39h6e9494a_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toml                      0.10.2                   pypi_0    pypi
tornado                   6.1              py39h89e85a6_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py39h6e9494a_4    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yfinance                  0.1.63                   pypi_0    pypi
zeromq                    4.3.4                h1c7c35f_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```
</p></details>

**Comment by kgugala** [comment]
This is caused by recent changes in pip. To be more precise it seems this commit in PIP https://github.com/pypa/pip/commit/f6b184ccaf464021e7633d15fa719dd35e164fdd breaks this. It adds special handling for links starting with `file` here https://github.com/pypa/pip/blame/main/src/pip/_internal/req/req_file.py#L514, so instead of going with simple `f.read()` path we were going through `session.get()`.
I Conda env resolver should either strip the `file:` prefix or change it to `file://`.

See also comment in pip issue https://github.com/pypa/pip/issues/10237

**Comment by mfansler** [comment]
I don't think Conda should be manipulating `file:` prefix as proposed here. 

The lines given in a `pip:` section are directly translated as input to Pip (via a temporary requirements.txt file), and therefore it falls on the end user to know the `pip install` syntax.  According to the response on the upstream issue, `file:requirements.txt` is simply invalid. So this proposal would in effect be asking Conda to implement a non-sanctioned extension of RFC8089 to support technically invalid syntax. If the PyPA doesn't want to implement it, I don't think Conda should be taking up their mantle.

**Comment by kgugala** [comment]
@mfansler I'm fine with updating my env yamls (actually already did it). Maybe Conda can throw an error (or at least a warning) if the entries in the pip section are incorrect? Currently we get quite obscure error from pip.

**Comment by drorata** [comment]
I made two changes attempts to the following line:

```
  - pip:
      - -r file:requirements.txt
```

### Option 1 ❌

Changed to:

```
  - pip:
      - -r file://requirements.txt
```

Didn't work and yielded the following error:

```
ValueError: non-local file URIs are not supported on this platform: 'file://requirements.txt'
```

### Option 2 ✅

```
  - pip:
      - -r requirements.txt
```

Resolved the issue. Honestly, I don't remember why I added the `file:` in the first place. I believe I found it in some (maybe old) `conda` documentation.

**Comment by jezdez** [comment]
This was at least fixed in the docs in #10820, thanks @mfansler!
