### ISSUE TITLE
When I update conda I get the error：TypeError: __init__() got an unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by BigtigerLi** [conda/conda#12770]
### What happened?

After I updated the conda version from 22.9 to 23.3.1, all conda-related commands could not be used, and an error was reported: `TypeError: __init__() got an unexpected keyword argument 'required'`:

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in generate_parser
        sub_parsers = p.add_subparsers(
      File "/public/home/ccli/.local/lib/python3.7/site-packages/argparse.py", line 1698, in add_subparsers
        action = parsers_class(option_strings=[], **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'required'

`$ /public/home/ccli/anaconda3/bin/conda info`
```

### Conda Details

<details>
<summary><code>conda info</code></summary>

```
active environment : base
    active env location : /public/home/ccli/anaconda3
            shell level : 1
       user config file : /public/home/ccli/.condarc
 populated config files : 
          conda version : 23.3.1
    conda-build version : 3.22.0
         python version : 3.8.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=2.6.32=0
                          __unix=0=0
       base environment : /public/home/ccli/anaconda3  (writable)
      conda av data dir : /public/home/ccli/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/ccli/anaconda3/pkgs
                          /public/home/ccli/.conda/pkgs
       envs directories : /public/home/ccli/anaconda3/envs
                          /public/home/ccli/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.8.5 Linux/2.6.32-504.el6.x86_64 centos/6.6 glibc/2.17
```

</details>

**Comment by kenodegard** [comment]
@BigtigerLi The problem comes from your `/public/home/ccli/.local` directory where you have Python 3.7 modules installed:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/public/home/ccli/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in generate_parser
        sub_parsers = p.add_subparsers(
      File "/public/home/ccli/.local/lib/python3.7/site-packages/argparse.py", line 1698, in add_subparsers
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

To resolve this please review the paths included in your `$PYTHONPATH` (if any) and your `$PATH` and optionally delete `/public/home/ccli/.local/lib/python3.7`.

**Comment by BigtigerLi** [comment]
Hi, I don't know where to install python3.7, I am not the installer of this conda.
PATH=/public/home/ccli/huangziying/cgmaptools-0.1.2:/public/home/ccli/huang
                          ziying/Python-2.7.14/lib:/public/home/ccli/yhfu/hliu/Gene_network/zlib
                          /bin:/public/home/ccli/yhfu/hliu/miRNA/02Software/randfold-2.0.1:/publ
                          ic/home/ccli/yhfu/hliu/miRNA/02Software/ViennaRNA/bin:/public/home/ccl
                          i/yhfu/hliu/miRNA/02Software/bowtie-1.3.1-linux-x86_64:/public/home/cc
                          li/yhfu/hliu/miRNA/02Software/mirdeep2_0_0_7:/public/home/ccli/softwar
                          e/RSeQC-2.6.4/public/home/ccli/bin/Python-2.7/bin:/public/home/ccli/so
                          ftware/Python-2.7.9:/public/home/ccli/software/sratoolkit/sratoolkit.2
                          .10.2-centos_linux64/bin:/public/home/ccli/tiancheng/meta/bin4/17_phyl
                          o/software/muscle:/public/home/ccli/tiancheng/software/fastp/fastp:/pu
                          blic/home/ccli/anaconda3/bin:/public/home/ccli/anaconda3/condabin:/pub
                          lic/home/ccli/anaconda3/bin:/usr/lib64/qt-3.3/bin:/public/software/mpi
                          /openmpi/1.6.5/intel/bin:/public/software/mpi/openmpi/1.6.5/gnu/bin:/o
                          pt/gridview/pbs/dispatcher-sched/bin:/opt/gridview/pbs/dispatcher-sche
                          d/sbin:/opt/gridview/pbs/dispatcher/bin/lsf_cmd:/opt/gridview/pbs/disp
                          atcher/bin:/opt/gridview/pbs/dispatcher/sbin:/public/software/compiler
                          /intel/composer_xe_2013_sp1.0.080/bin/intel64:/opt/clusconf/bin:/usr/b
                          in:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/ibutils/bin:/public/home/
                          ccli/bin:/public/home/ccli/software/mirdeep2_0_0_8/bin:/public/home/cc
                          li/yhfu/01software/00homemade:/public/home/ccli/yhfu/01software/Trimmo
                          matic-0.36:/public/home/ccli/bin/bedtools-2.17.0/bin:/public/home/ccli
                          /yhfu/01software/MACS-1.4.2/bin:/public/home/ccli/yhfu/01software/stri
                          ngtie-1.3.3b.Linux_x86_64:/public/home/ccli/huangziying/Python-2.7.14:
                          /public/home/ccli/zhaowenjuan/salmon/software/salmon-latest_linux_x86_
                          64/bin:/public/home/ccli/zhaowenjuan/software/sambamba:/public/home/cc
                          li/wzluo/miniconda3/envs/zwj_homer/bin/bin:/public/home/ccli/zhaowenju
                          an/software/macs2/MACS-2.2.7.1/bin:/public/home/ccli/pip/pip.ini:/publ
                          ic/home/ccli/tiancheng/sratoolkit.2.9.2-centos_linux64/bin:/public/hom
                          e/ccli/tiancheng/phage/01_spades/SPAdes-3.15.0-Linux/bin:/public/home/
                          ccli/tiancheng/phage/17_bwa/bwa-0.7.17:/public/home/ccli/tiancheng/sof
                          tware/fastp:/public/home/ccli/tiancheng/meta/bin4/17_phylo/software/us
                          earch
               PYTHONPATH=:/public/home/ccli/yhfu/01software/MACS-1.4.2/lib/python2.6/site-packa
                          ges/:/public/home/ccli/software/RSeQC-2.6.4/public/home/ccli/bin/Pytho
                          n-2.7/lib/python2.7/site-
                          packages/:/public/home/ccli/.local/lib/python3.7/site-packages
This is so complicated that I can't understand it. Is it enough to delete /public/home/ccli/.local/lib/python3.7?

**Comment by BigtigerLi** [comment]
hi，I don't know where to install python3.7, because I am not the installer of this conda.
`PATH=/public/home/ccli/huangziying/cgmaptools-0.1.2:/public/home/ccli/huang
                          ziying/Python-2.7.14/lib:/public/home/ccli/yhfu/hliu/Gene_network/zlib
                          /bin:/public/home/ccli/yhfu/hliu/miRNA/02Software/randfold-2.0.1:/publ
                          ic/home/ccli/yhfu/hliu/miRNA/02Software/ViennaRNA/bin:/public/home/ccl
                          i/yhfu/hliu/miRNA/02Software/bowtie-1.3.1-linux-x86_64:/public/home/cc
                          li/yhfu/hliu/miRNA/02Software/mirdeep2_0_0_7:/public/home/ccli/softwar
                          e/RSeQC-2.6.4/public/home/ccli/bin/Python-2.7/bin:/public/home/ccli/so
                          ftware/Python-2.7.9:/public/home/ccli/software/sratoolkit/sratoolkit.2
                          .10.2-centos_linux64/bin:/public/home/ccli/tiancheng/meta/bin4/17_phyl
                          o/software/muscle:/public/home/ccli/tiancheng/software/fastp/fastp:/pu
                          blic/home/ccli/anaconda3/bin:/public/home/ccli/anaconda3/condabin:/pub
                          lic/home/ccli/anaconda3/bin:/usr/lib64/qt-3.3/bin:/public/software/mpi
                          /openmpi/1.6.5/intel/bin:/public/software/mpi/openmpi/1.6.5/gnu/bin:/o
                          pt/gridview/pbs/dispatcher-sched/bin:/opt/gridview/pbs/dispatcher-sche
                          d/sbin:/opt/gridview/pbs/dispatcher/bin/lsf_cmd:/opt/gridview/pbs/disp
                          atcher/bin:/opt/gridview/pbs/dispatcher/sbin:/public/software/compiler
                          /intel/composer_xe_2013_sp1.0.080/bin/intel64:/opt/clusconf/bin:/usr/b
                          in:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/ibutils/bin:/public/home/
                          ccli/bin:/public/home/ccli/software/mirdeep2_0_0_8/bin:/public/home/cc
                          li/yhfu/01software/00homemade:/public/home/ccli/yhfu/01software/Trimmo
                          matic-0.36:/public/home/ccli/bin/bedtools-2.17.0/bin:/public/home/ccli
                          /yhfu/01software/MACS-1.4.2/bin:/public/home/ccli/yhfu/01software/stri
                          ngtie-1.3.3b.Linux_x86_64:/public/home/ccli/huangziying/Python-2.7.14:
                          /public/home/ccli/zhaowenjuan/salmon/software/salmon-latest_linux_x86_
                          64/bin:/public/home/ccli/zhaowenjuan/software/sambamba:/public/home/cc
                          li/wzluo/miniconda3/envs/zwj_homer/bin/bin:/public/home/ccli/zhaowenju
                          an/software/macs2/MACS-2.2.7.1/bin:/public/home/ccli/pip/pip.ini:/publ
                          ic/home/ccli/tiancheng/sratoolkit.2.9.2-centos_linux64/bin:/public/hom
                          e/ccli/tiancheng/phage/01_spades/SPAdes-3.15.0-Linux/bin:/public/home/
                          ccli/tiancheng/phage/17_bwa/bwa-0.7.17:/public/home/ccli/tiancheng/sof
                          tware/fastp:/public/home/ccli/tiancheng/meta/bin4/17_phylo/software/us
                          earch
               PYTHONPATH=:/public/home/ccli/yhfu/01software/MACS-1.4.2/lib/python2.6/site-packa
                          ges/:/public/home/ccli/software/RSeQC-2.6.4/public/home/ccli/bin/Pytho
                          n-2.7/lib/python2.7/site-
                          packages/:/public/home/ccli/.local/lib/python3.7/site-packages`
This is so complicated that I can't understand it. Is it enough to delete /public/home/ccli/.local/lib/python3.7?

**Comment by BigtigerLi** [comment]
@kenodegard Thank you very much for your help, I have solved this problem!
