### ISSUE TITLE
`conda doctor --fix`: missing-files fixer fails with `install() missing 1 required positional argument: parser`

### ISSUE THREAD

**Issue by jezdez** [conda/conda#15669]
### What happened?

Running `conda doctor --fix` in conda 26.1.0 fails when attempting to fix packages with missing files:

```
Environment Health Report for: /path/to/env

✅ There are no packages with altered files.

✅ The environment is consistent.

✅ The environment is listed in the environments.txt file.

✅ File locking is supported.

❌ Missing Files:

python.app-3-py313h80987f9_2: 7

✅ No pinned specs found in /path/to/env/conda-meta/pinned.

============================================================
Running fixes...
============================================================

No packages with altered files found.
No inconsistent packages found.
Environment is already registered in environments.txt: /path/to/env
Found 1 package(s) with missing files:
  python.app-3-py313h80987f9_2: 7 missing file(s)

Reinstall these packages to restore missing files? (y/[n])? y

WARNING conda.plugins.subcommands.doctor:execute(120): Error running fix: missing-files (install() missing 1 required positional argument: 'parser')
No pinned file found at /path/to/env/conda-meta/pinned
```

### Expected behavior

The missing files should be fixed by reinstalling the affected package.

### Root cause

In `conda/cli/install.py`, the `reinstall_packages()` function calls `install(args)` on line 92, but the `install()` function signature requires two positional arguments: `def install(args, parser, command="install")`.

The `parser` argument is missing in the call.

### Conda Info

conda 26.1.0, macOS

### Additional Context

This regression was introduced when `reinstall_packages` was moved in commit 301ec4376. The fix should make the `parser` argument optional in `install()` since it's only used for the deprecated `--clone` path.

**Comment by kenodegard** [comment]
Closing since #15670 has been merged

**Comment by RidaZubair** [comment]
@kenodegard @jezdez I'm still seeing this issue on conda 26.1.1.65+g78a3de60c
```
"(base) ridazubair@Ridas-MacBook-Pro Downloads %  echo y | conda doctor -n doctor-test --fix             
Environment Health Report for: /Users/ridazubair/miniconda3/envs/doctor-test

✅ There are no packages with altered files.

✅ The environment is consistent.

✅ The environment is listed in the environments.txt file.

✅ File locking is supported.

❌ Missing Files:

python-3.12.13-hd7e0f33_1: 1

✅ No pinned specs found in /Users/ridazubair/miniconda3/envs/doctor-test/conda-meta/pinned.

============================================================
Running fixes...
============================================================

No packages with altered files found.
No inconsistent packages found.
Environment is already registered in environments.txt: /Users/ridazubair/miniconda3/envs/doctor-test
Found 1 package(s) with missing files:
  python-3.12.13-hd7e0f33_1: 1 missing file(s)

Reinstall these packages to restore missing files? (y/[n])? 
WARNING conda.plugins.subcommands.doctor:execute(120): Error running fix: missing-files ('Namespace' object has no attribute 'use_local')
No pinned file found at /Users/ridazubair/miniconda3/envs/doctor-test/conda-meta/pinned"
```
