### PR TITLE
Don’t instantiate the solver backend for getting the user-agent.

### LINKED ISSUE #12103: Solver plugin hook incompatible with user_agent feature
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When trying to use the conda solver plugin hook, the `user_agent` method is called on an instance of the backend, even though the API requires it to be called on the backend class itself, since it's a staticmethod.

Exception:

```
Traceback (most recent call last):
  File "/opt/conda-src/conda/base/context.py", line 849, in user_agent
    user_agent_str += f" {solver_backend().user_agent()}"
TypeError: __init__() missing 2 required positional arguments: 'prefix' and 'channels'
```

### Conda Info

_No response_

### Conda Config

_No response_

### Conda list

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jezdez**
### Description

Updates the call of the user_agent staticmethod to be done on the class, not the instance, as incorrectly introduced in https://github.com/conda/conda/commit/ba7d9bc1b1516a48b2579ebb0d068986469280c3#diff-b088be378fc4d3c8240b5a24fd9d51409bb64226eb874be18a10eafadec79f78L850-R849.

Fix #12103

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [x] Add / update necessary tests?
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

File: tests/plugins/test_solvers.py [hunk 1]
```diff
@@ -62,6 +70,13 @@ def test_get_cached_solver_backend(plugin_manager, mocker):
     assert mocked.call_count == 1  # real caching!
 
 
+def test_solver_user_agent(plugin_manager, monkeypatch):
+    plugin = VerboseSolverPlugin()
+    plugin_manager.register(plugin)
+    monkeypatch.setattr(context, "solver", "verbose-classic")
+    assert verbose_user_agent in context.user_agent
```
Comment (jaimergp) [inline tests/plugins/test_solvers.py:77]: `user_agent` is memoized, so it might be returning the old value before you patched `solver` :/

**Review by jaimergp — APPROVED** [review]

File: tests/plugins/test_solvers.py (hunk 1 above)
Comment (jezdez) [reply tests/plugins/test_solvers.py:77]: okay, lemme work around that..

Comment (jezdez) [reply tests/plugins/test_solvers.py:81]: done in https://github.com/conda/conda/pull/12104/commits/db50fde447b597da4ab631382002a98b22abf90f

File: tests/plugins/test_solvers.py [hunk 2]
```diff
@@ -62,6 +70,17 @@ def test_get_cached_solver_backend(plugin_manager, mocker):
...
 
+def test_solver_user_agent(plugin_manager, monkeypatch):
+    plugin = VerboseSolverPlugin()
+    plugin_manager.register(plugin)
+    monkeypatch.setattr(context, "solver", "verbose-classic")
+    # context.user_agent is a memoizedproperty, which may have been cached from
+    # previous test runs. We're checking here and clear the cache if needed.
+    if "__user_agent" in context._cache_:
+        del context._cache_["__user_agent"]
+    assert verbose_user_agent in context.user_agent
```
Comment (jaimergp) [inline tests/plugins/test_solvers.py:81]: Should we clear the cache afterwards too?

Comment (jezdez) [reply tests/plugins/test_solvers.py:88]: yep, https://github.com/conda/conda/pull/12104/commits/c74065797f87e80c567bb0ab5962ef6ad8eb5838

**Review by jaimergp — APPROVED** [review]
