### ISSUE TITLE
module 'configparser' has no attribute 'RawConfigParser'

### ISSUE THREAD

**Issue by kingkaos** [conda/conda#10543]
## Current Behavior
Hello,
I created a virtual environment with conda and python 3.8.3 using conda create --prefix ./venv python==3.8.3 and afterwards I just wanted to use pip to install packages. It seems that something is broken since every package I try to install fails with AttributeError: module 'configparser' has no attribute 'RawConfigParser'.
Even when asking for version number with pip -V or pip --version I got the same error.
pip was added to the environment successfully. Removing pip and reinstalling did not fix it.
pip works with python 3.9.1 but for some package dependencies I have to stick to Python 3.8.3
Any suggest to overcome this issue?

Thank you.

### Steps to Reproduce

Error using pip

```
conda create --prefix ./venv python==3.8.3
./venv/bin/pip --version
```

It also fails with same error using

```
conda create --prefix ./venv python==3.8.3
conda activate ./venv
pip -V
```

## Expected Behavior

Get current pip version

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : /Users/dc/dev/tmp/venv
    active env location : /Users/dc/dev/tmp/venv
            shell level : 2
       user config file : /Users/dc/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/homebrew/Caskroom/miniconda/base  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/pkgs
                          /Users/dc/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniconda/base/envs
                          /Users/dc/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : /Users/dc/.netrc
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/dc/dev/tmp/venv:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.1.19            hecd8cb5_0    defaults
certifi                   2020.12.5        py38hecd8cb5_0    defaults
libcxx                    10.0.0                        1    defaults
libedit                   3.1.20191231         h1de35cc_1    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1j               h9ed2024_0    defaults
pip                       21.0.1           py38hecd8cb5_0    defaults
python                    3.8.3                h26836e1_2    defaults
readline                  8.1                  h9ed2024_0    defaults
setuptools                52.0.0           py38hecd8cb5_0    defaults
sqlite                    3.33.0               hffcf06c_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</p></details>
