### ISSUE TITLE
Conda Build with conda 23.10 is failing on MacOS x86 and M1

### ISSUE THREAD

**Issue by atalman** [conda/conda#13304]
### What happened?

We have following workflows started failing 2 days ago. The only change is the conda update to 23.10.
Workflow:
https://github.com/pytorch/audio/actions/runs/6802721295/job/18496446100#step:10:87
Error:
```
conda run -p /Users/runner/work/_temp/conda_environment_6802721295 conda build -c defaults -c pytorch-test --no-anaconda-upload --python 3.8 --output-folder distr/ packaging/torchaudio
Traceback (most recent call last):
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda_build/conda_interface.py", line 14, in try_exports
    return getattr(import_module('conda.exports'), attr)
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda/deprecations.py", line 242, in __getattr__
    raise AttributeError(f"module '{fullname}' has no attribute '{name}'")
AttributeError: module 'conda.exports' has no attribute 'get_prefix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/_temp/conda_environment_[68](https://github.com/pytorch/audio/actions/runs/6802721295/job/18496446100#step:10:69)02[72](https://github.com/pytorch/audio/actions/runs/6802721295/job/18496446100#step:10:73)1295/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "/Users/runner/work/_temp/conda_environment_6[80](https://github.com/pytorch/audio/actions/runs/6802721295/job/18496446100#step:10:81)2721295/lib/python3.8/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda_build/conda_interface.py", line 119, in <module>
    context_get_prefix = try_exports("conda.base.context", "get_prefix")
  File "/Users/runner/work/_temp/conda_environment_6802721295/lib/python3.8/site-packages/conda_build/conda_interface.py", line 16, in try_exports
    return getattr(import_module(module), attr)
AttributeError: module 'conda.base.context' has no attribute 'get_prefix'

ERROR conda.cli.main_run:execute(47): `conda run conda build -c defaults -c pytorch-test --no-anaconda-upload --python 3.8 --output-folder distr/ packaging/torchaudio` failed. (See above for error)
```

If I pin conda to 23.7.3 everything passes. Here is passing workflow:
https://github.com/pytorch/test-infra/actions/runs/6804636085/job/18502599336?pr=4713

**Comment by kenodegard** [comment]
@atalman correct, `conda 23.10.0` is incompatible with `conda-build 3.21` which is what y'all are currently pinned to, I would first try unpinning conda-build

**Comment by atalman** [comment]
Ok Thank you @kenodegard will try to do that

**Comment by huydhn** [comment]
I think the issue has been resolved on our end, so do you want to close it @atalman?
